Change the target data-layout to match LLVM’s
Current nightly rejects the one we had until now due to the lack of
-Fn32, add it so it is happy again.

Here is the error we get without this commit:
```
error: data-layout for target `powerpc-unknown-eabi-2922781650972509521`, `E-m:e-p:32:32-i64:64-n32`, differs from LLVM target's `powerpc-unknown-eabi` default layout, `E-m:e-p:32:32-Fn32-i64:64-n32`
```